# vim:set ft=dockerfile:
FROM postgres:12.2

ENV BUILD_DEPS \
	git \
	cmake \
	wget \
	build-essential \
	ca-certificates \
	libpq-dev \
	postgresql-server-dev-12

ENV LANG zh_CN.utf8
ENV TIMEZONE=Asia/Shanghai
RUN set -eux \
	; ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
  	; echo "$TIMEZONE" > /etc/timezone \
	; sed -i /etc/locale.gen \
		-e 's/# \(en_US.UTF-8 UTF-8\)/\1/' \
		-e 's/# \(zh_CN.UTF-8 UTF-8\)/\1/' \
	; locale-gen \
	; apt-get update \
	; apt-get install -y --no-install-recommends \
		postgresql-plpython3-12 postgresql-12-python3-multicorn \
		python3-pip python3-setuptools \
		${BUILD_DEPS:-} \
	; pip3 --no-cache-dir install \
		numpy requests pyyaml furl \
		cachetools more-itertools PyParsing \
	\
	; build_dir=/root/build \
	; mkdir -p $build_dir \
	; cd $build_dir \
	; git clone https://github.com/postgrespro/rum.git \
	; cd rum \
	; make USE_PGXS=1 \
	; make USE_PGXS=1 install \
	; cd $build_dir \
	; git clone https://github.com/eulerto/wal2json.git \
	; cd wal2json \
	; USE_PGXS=1 make \
	; USE_PGXS=1 make install \
	; cd $build_dir \
	; git clone https://github.com/jaiminpan/pg_jieba \
  	; cd pg_jieba \
  	; git submodule update --init --recursive  \
	; mkdir build \
	; cd build \
	; cmake .. \
		-DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/12/server \
	; make \
	; make install \
	; rm -rf $build_dir \
	\
	; apt-get purge -y --auto-remove ${BUILD_DEPS:-} \
	; apt-get clean -y && rm -rf /var/lib/apt/lists/*


COPY docker-entrypoint-deb.sh /usr/local/bin/docker-entrypoint.sh
RUN ln -sf usr/local/bin/docker-entrypoint.sh / # backwards compat

ENV PGC_SHARED_BUFFERS=128MB
ENV PGC_WAL_LEVEL=logical
ENV PGC_MAX_REPLICATION_SLOTS=10
#ENV PGC_SHARED_PRELOAD_LIBRARIES="'pg_stat_statements,pg_jieba.so'"
