# vim:set ft=dockerfile:
FROM python:3.7.4-alpine3.10

# alpine includes "postgres" user/group in base install
#   /etc/passwd:22:postgres:x:70:70::/var/lib/postgresql:/bin/sh
#   /etc/group:34:postgres:x:70:
# the home directory for the postgres user, however, is not created by default
# see https://github.com/docker-library/postgres/issues/274
RUN set -ex; \
	postgresHome="$(getent passwd postgres)"; \
	postgresHome="$(echo "$postgresHome" | cut -d: -f6)"; \
	[ "$postgresHome" = '/var/lib/postgresql' ]; \
	mkdir -p "$postgresHome"; \
	chown -R postgres:postgres "$postgresHome"

ENV LANG zh_CN.utf8

RUN set -eux \
  ; mkdir /docker-entrypoint-initdb.d \
  ; sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
  ; apk add --no-cache --virtual .install-deps \
        unzip \
		bison \
		coreutils \
		dpkg-dev dpkg \
		flex \
		gcc \
        g++ \
		make \
        linux-headers \
        musl-dev \
  ; pip --no-cache-dir install \
		numpy requests pyyaml furl \
		cachetools more-itertools PyParsing \
  ; apk add --no-cache --virtual .postgresql-rundeps \
		bash \
		su-exec \
# tzdata is optional, but only adds around 1Mb to image size and is recommended by Django documentation:
# https://docs.djangoproject.com/en/1.10/ref/databases/#optimizing-postgresql-s-configuration
		tzdata \
  ; cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  ; echo "Asia/Shanghai" > /etc/timezone \
  ; apk del .install-deps